BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "GameOptions" (
	"OptionID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"Parameter"	TEXT NOT NULL,
	"PValue"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "QuestionData" (
	"QuestionID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"RealmNumber"	INTEGER NOT NULL,
	"Question"	TEXT NOT NULL,
	"Answer"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "PlayerData" (
	"PlayerID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"TotalScore"	INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "LevelData" (
	"LevelID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"BestScore"	INTEGER NOT NULL DEFAULT 0,
	"RoundTime"	INTEGER NOT NULL DEFAULT 0,
	"PointMultiplier"	INTEGER NOT NULL DEFAULT 1,
	"UnlockLevelAt"	INTEGER NOT NULL DEFAULT 0

);
COMMIT;
